project/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }

  resources :users, path_names: { edit: 'change_password' } do
    get 'map' => 'users#map'
    resources :blacklists, only: [:create]
  end
  post '/create_user' => 'users#create', as: :create_user

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    get 'map' => 'posts#map'
    resources :inappropriate_content, only: [:new, :create]
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, only: [:create, :destroy]
    resources :followers, only: [:create, :destroy]
    resources :shares, only: [:create]
    resources :dumpsters, only: [:create]
  end
  

  resources :administrators, path_names: { edit: 'change_password' } do
    get 'map' => 'administrators#map'
    get 'map_edit' => 'administrators#map_edit'
    put 'map_edit' => 'administrators#map_update'

  end

  resources :blacklists, only: [:index, :destroy]
  resources :dumpsters, only: [:index, :destroy]
  resources :abusive_contents, only: [:new, :create]



  root 'home#index'

  get 'terms_of_services' => 'registrations#terms_of_services'


  get 'aup' => 'registrations#aup'
  get 'notifications' => 'notifications#index'

  delete '/log_in' => 'sessions#destroy', as: :log_out

end

project/app/models/blacklist.rb
class Blacklist < ApplicationRecord
 	belongs_to :user
 	
	validates :user_id, numericality: {message: "The User ID must be an integer."},
		uniqueness: {with: true, message: "The User is already on the Blacklist."}

	after_create :inactive_user
	after_create :create_banned_user

	after_destroy :active_user

	private def inactive_user
		for post in Post.all do

			if post[:user_id] == user_id

				if post[:inappropriate] == false

					Dumpster.create(post_id: post.id)
				end
			end
		end

		User.update(user_id, :status => false)

	end

	private def create_banned_user
		BannedUser.create(user_id: user_id)
	end

	private def active_user
		User.update(user_id, :status => true)

	end

	




end

project/app/controllers/blacklists_controller.rb
class BlacklistsController < ApplicationController
	before_action :authorize_admin

	def index
		users = User.search(params[:search])
    	@blacklists = []

    	for user in users do 
    		if user.status == false 
    			@blacklists << user
    		end
    	end
	end

	def create
		@user = User.find(params[:user_id])
		@black = Blacklist.create(user_id: @user.id)
		if @black.save(user_id: @user.id)

	    	flash[:success] = "This user is now on the Blacklist."
	    	redirect_to blacklists_path
	    else
	    	flash.now[:error] = "Cannot send this user to the Blacklist."
	    	render :index
	    end
		
	end

	def destroy
		
  		@blacklist = Blacklist.find(params[:id])
  		@user = User.find(@blacklist.user_id)
  		@blacklist.destroy
  		if @blacklist.destroy
  		  #@user.update(status: true)
	      flash[:success] = "Successfully activated the user."
	      redirect_to users_path
	    end
	end
end

project/app/helpers/blacklists_helper.rb
module BlacklistsHelper
end

project/app/views/blacklists/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div id="kconteiner">
  <div class = "dark_box dark_box2">
    <div class = "titles">
      <h1>Blacklist</h1>
    </div>
    
    <div class="search-container">
      <form class="example">
        <%= form_tag(blacklists_path, method: :get) do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search by name or city.." %>
          <button class="button" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        <% end %><br>
      </form>
    </div>

     
    <div class="table">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">City</th>        
            <th scope="col">Country</th>
            <th scope="col">Last access</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
       
          <% @blacklists.each do |blacklist| %>
          <tr>
            <td scope="row"><span class="glyphicon glyphicon-user"></span></td>
            <td><strong><%= blacklist.name%></strong></td>
            <td><strong><%= blacklist.email %></strong></td>
            <td><strong><%= blacklist.city%></strong></td>
            <td><strong><%= blacklist.country %></strong></td>
            <td>
              <% if blacklist.last_sign_in_at %>
                <strong><%= blacklist.last_sign_in_at.strftime( '%d/%m/%Y %H:%M' ) %></strong>
              <% else %>
                <strong><%= 'Has not logged yet.' %></strong>
              <% end %>
            </td>
            <td><%= link_to user_path(blacklist) do %>
                  <span class="glyphicon glyphicon-eye-open"></span>
                <% end %></td>
            <% g=Geofence.find_by(user_id: current_user.id) %>
            <% u=Geofence.find_by(user_id: blacklist.id) %>
            <% if u && g%>
              <% if ((g.longitude.to_f.abs - 0.1) <= u.longitude.to_f.abs && (g.longitude.to_f.abs + 0.1 >= u.longitude.to_f.abs && (g.latitude.to_f.abs - 0.1) <= u.latitude.to_f.abs && (g.latitude.to_f.abs + 0.1) >= u.latitude.to_f.abs) && current_user.adm) || (current_user.super_adm || current_user.id == blacklist.id)  %>
                <td><%= link_to edit_user_path(blacklist) do %>
                      <span class="glyphicon glyphicon-edit"></span>
                    <% end %></td>
                <% if Blacklist.find_by(user_id: blacklist.id) %>
                  <% b = Blacklist.find_by(user_id: blacklist.id) %>
                  <td><%= link_to blacklist_path(b),
                        method: :delete,
                        data: { confirm: 'Are you sure you want to active this user?' } do %>
                      <span class="glyphicon glyphicon-check"></span>
                    <% end %></td>
                <% end %>           
                <td><%= link_to user_path(blacklist),
                        method: :delete,
                        data: { confirm: 'Are you sure you want to delete this user?' } do %>
                      <span class="glyphicon glyphicon-trash"></span>
                    <% end %></td>
              <% else %>
                <td>
                <td>
                <td>   
              <% end %>

            <% else %>
                <td><%= link_to edit_user_path(blacklist) do %>
                      <span class="glyphicon glyphicon-edit"></span>
                    <% end %></td>
                <% if Blacklist.find_by(user_id: blacklist.id) %>
                  <% b = Blacklist.find_by(user_id: blacklist.id) %>
                  <td><%= link_to blacklist_path(b),
                        method: :delete,
                        data: { confirm: 'Are you sure you want to active this user?' } do %>
                      <span class="glyphicon glyphicon-check"></span>
                    <% end %></td>
                <% end %>           
                <td><%= link_to user_path(blacklist),
                        method: :delete,
                        data: { confirm: 'Are you sure you want to delete this user?' } do %>
                      <span class="glyphicon glyphicon-trash"></span>
                    <% end %></td> 
            <% end %>              
            
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>