project/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }

  resources :users, path_names: { edit: 'change_password' } do
    get 'map' => 'users#map'
    resources :blacklists, only: [:create]
  end
  post '/create_user' => 'users#create', as: :create_user

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    get 'map' => 'posts#map'
    resources :inappropriate_content, only: [:new, :create]
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, only: [:create, :destroy]
    resources :followers, only: [:create, :destroy]
    resources :shares, only: [:create]
    resources :dumpsters, only: [:create]
  end
  

  resources :administrators, path_names: { edit: 'change_password' } do
    get 'map' => 'administrators#map'
    get 'map_edit' => 'administrators#map_edit'
    put 'map_edit' => 'administrators#map_update'

  end

  resources :blacklists, only: [:index, :destroy]
  resources :dumpsters, only: [:index, :destroy]
  resources :abusive_contents, only: [:new, :create]



  root 'home#index'

  get 'terms_of_services' => 'registrations#terms_of_services'


  get 'aup' => 'registrations#aup'
  get 'notifications' => 'notifications#index'

  delete '/log_in' => 'sessions#destroy', as: :log_out

end

project/app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_many :likes
	has_many :dislikes
	has_many :inappropriate_contents
	has_many :notification_admins
	has_many :notification_super_admins
	has_many :notifications
	has_many :shares
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

 	has_attached_file :file
 	validates_attachment_content_type :file, content_type: "application/pdf"

	validates :title, presence: true, length: { maximum: 30, message: "The post's title should have no more than 30 characters." }
	validates :user_id, numericality: {message: "The User ID must be an integer."}
	validates :description, presence: true
	validates :close, inclusion: { in: [ true, false ], message: "It must be true or false" }
	validates :unresolved, inclusion: { in: [ true, false ], message: "It must be true or false" }
	validates :inappropriate, inclusion: { in: [ true, false ], message: "It must be true or false" }

	#after_validation :innactive_user
	after_validation :not_inappropriate, :on => :create

	after_create :create_user_profile
	after_create :create_geo

	after_update :update_geo
	after_update :notify_follower_update
	after_update :create_post_dumpster
	after_update :destroy_post_dumpster

	before_destroy :destroy_all_things


  	private def not_inappropriate

		if inappropriate == true
			errors.add(:inappropriate, "The Post must not be inappropriate when it's being created.")
		end

  	end

	private def innactive_user

		contador = 0
		for user in User.all
			if user[:id] == user_id
				contador = 1
			end
		end

		if contador == 1
			user = User.find(user_id)
			status = user[:status]

			if status == false
				errors.add(:user_id, "A User that is innactive cannot create a Post.")
			end
		end
	end

	private def create_geo
		if gps != nil
			Geo.create(post_id: id, address: gps)
		end
		
	end

	private def update_geo
		if gps != nil
			geo = Geo.find_by(post_id: id)
			if geo != nil
				geo.update(address: gps)
			else
				Geo.create(post_id: id, address: gps)
			end
		end
		
	end

	private def create_user_profile
		user = User.find(user_id)
		text = user[:name] +" created the post '" + title
		UserProfile.create(user_id: user_id, description: text, help: "post")
	end

	def self.search(title)
	  if title
	    where('title LIKE ? OR description Like ?', "%#{title}%", "%#{title}%")
	  else
	    all
	  end
	end

	def notify_user(action1, action2)
		n = Notification.create(user_id: self[:user_id], post_id: self[:id], description: action1, help: action2)
	end

	def notify_tag(action1, userid, action2)
		n = Notification.create(user_id: userid, post_id: self[:id], description: action1, help: action2)
	end


	def notify_follower(action1, action2)
		for follower in Follower.all
			if follower[:post_id] == self[:id]
				Notification.create(user_id: follower[:user_id], post_id: self[:id], description: action1, help: action2)
			end
		end
	end

	def notify_follower_update
		text = "The post '" + title + "' has been updated"
		for follower in Follower.all
			if follower[:post_id] == self[:id]
				Notification.create(user_id: follower[:user_id], post_id: self[:id], description: text, help:"update")
			end
		end
	end

	private def destroy_post_dumpster
		if inappropriate == false
			for post in Dumpster.all do
				if post[:post_id] == id
					Dumpster.destroy(post[:id])
				end
			end
		end
	end

	private def create_post_dumpster
		if inappropriate == true
			Dumpster.create(post_id: id)
		end
	end

	private def destroy_all_things
		for comment in Comment.all do
			if comment[:post_id] == id
				Comment.destroy(comment[:id])
			end
		end
		for like in Like.all do
			if like[:post_id] == id
				Like.destroy(like[:id])
			end
		end
		for dislike in Dislike.all do
			if dislike[:post_id] == id
				Dislike.destroy(dislike[:id])
			end
		end
		for inapp in InappropriateContent.all do
			if inapp[:post_id] == id
				InappropriateContent.destroy(inapp[:id])
			end
		end
		for dump in Dumpster.all do
			if dump[:post_id] == id
				Dumpster.destroy(dump[:id])
			end
		end
		for notification in Notification.all do
			if notification[:post_id] == id
				Notification.destroy(notification[:id])
			end
		end
		for follower in Follower.all do
			if follower[:post_id] == id
				Follower.destroy(follower[:id])
			end
		end
		for share in Share.all do
			if share[:post_id] == id
				Share.destroy(share[:id])
			end
		end
		for wall in UserProfile.all do
			if wall[:post_id] == id
				UserProfile.destroy(wall[:id])
			end
		end
		for geo in Geo.all do
			if geo[:post_id] == id
				Geo.destroy(geo[:id])
			end
		end
	end

end

project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy]
	skip_before_action :authenticate_user!, :only => [:index, :show, :map]
	def index
		posts = Post.search(params[:search])
		users = User.search(params[:search])
		@posts = []

		for post in posts do

			if post.inappropriate == false
				@posts << post
			end
		end
		for user in users do
			if user.status == true
				for post in Post.all do
					if post.inappropriate == false && post.user_id == user.id && @posts.exclude?(post)
						@posts << post
					end
				end
			end
		end


	end


	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end


	def create
		@post = Post.new(post_params)
	 	if @post.save(post_params)
	    	flash[:success] = "The post was created successfully."
	    	redirect_to @post
	    else
	    	flash.now[:error] = "Cannot create this post."
	    	render :new
	    end
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
	      flash[:success] = "The post was updated successfully."
	      redirect_to @post
	    else
	      flash[:error] = "Cannot update this post."
	      render :edit
	    end
	end


	def destroy
  		@post = Post.find(params[:id])
  		@post.destroy
  		if @post.destroy
	      flash[:success] = "The post was destroyed successfully."
	      redirect_to posts_path
	    end
	end

	def innapropriate
	
		@inap = InappropriateContent.new

	end

	def map
		@post = Post.find(params[:post_id])
	end


	private
	  def post_params
	  	if current_user == nil
	  		params.require(:post).permit(:title, :description, :city, :country, :gps, :file, :avatar, :close, :user_id, :inappropriate, :unresolved)
	  	else
	    	params.require(:post).permit(:title, :description, :city, :country, :gps, :file, :avatar, :close, :user_id, :inappropriate, :unresolved).merge(user_id: current_user[:id])
		end

	  end
end

project/app/helpers/posts_helper.rb
module PostsHelper
end

project/app/views/posts/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div id="kconteiner">
  <div class = "box box2">
    <div class = "titles">
      <h1>Posts</h1>
    </div>
    <div class="search-container">
      <form class="example">
        <%= form_tag(posts_path, method: :get) do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search by title, description or author.." %>
          <button class="button" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        <% end %><br>
      </form>
    </div>

    <% if (current_user != nil) && (current_user[:status] == true) %>    
      <%= link_to new_post_path do%>
        <span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> New Post
      <% end %>

    <% end %>
    <div class = "table">
      <table class = "table">
        <thead>
          <tr>
            <th></th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Description</th>
            <th scope="col">Status</th>
            <%if current_user != nil %>
              <th></th>
              <th></th>
            <% end %>
            <% if (current_user != nil) && (current_user[:adm] == true) %>
              <th></th>
            <% end %>
            <th></th>
          </tr>
        </thead>
        <tbody>
       
          <% @posts.each do |post| %>
          <tr>
            <td scope="row"><span class="glyphicon glyphicon-file"></span></td>
            <td><strong><%= post.title %></strong></td>
            <td><strong><%= User.find(post.user_id)[:name] %></strong></td>
            <% d = "" %>
            <% contador = 0 %>
            <% for i in post.description.split('') %>
              <% d << i %>
              <% contador += 1 %>
              <% if contador == 20 %>
                <% d += '...' %>
                <% break %>
              <% end %>
            <% end %>

            <td><strong><%= d %></strong></td>
            <% if post.close == true %>
              <td><strong> Closed </strong></td>
            <% else %>
              <td><strong> Opened </strong></td>
            <% end %>

            <td><%= link_to post_path(post) do %>
                  <span class="glyphicon glyphicon-eye-open"></span>
                <% end %></td>

            <% if current_user %>
              <% g=Geofence.find_by(user_id: current_user.id) %>
              <% p=Geo.find_by(post_id: post.id) %>
            <% else %>
              <%g=nil%>
              <%p=nil%>
            <%end%>

            <% if p && g%>

              <% if ((g.longitude.to_f.abs - 0.1) <= p.longitude.to_f.abs && (g.longitude.to_f.abs + 0.1 >= p.longitude.to_f.abs && (g.latitude.to_f.abs - 0.1) <= p.latitude.to_f.abs && (g.latitude.to_f.abs + 0.1) >= p.latitude.to_f.abs) && current_user.adm) || (current_user.super_adm || current_user.id == post.user_id)  %>
              <td>
                <% if (current_user != nil) && ((current_user[:adm] == true) || User.find(post.user_id)[:id] == current_user.id)  %> 
                  <%= link_to edit_post_path(post) do %>
                    <span class="glyphicon glyphicon-edit"></span>
                  <% end %></td>

                <% end %>
                

              <% if (current_user != nil) && (current_user[:adm] == true) %> 
                <td>
                <%= link_to post_dumpsters_path(post), 
                    method: :create,
                    data: { confirm: 'Are you sure you want to send this post to the Dumpster?' }  do %>
                  <span class="glyphicon glyphicon-ban-circle"></span>
                <% end %>
                </td>
              <% end %>
              
              <td>
                <% if (current_user != nil) && ((current_user[:adm] == true) || User.find(post.user_id)[:id] == current_user.id) %> 
                  <%= link_to post_path(post),
                      method: :delete,
                      data: { confirm: 'Are you sure you want to delete this post?' } do %>
                    <span class="glyphicon glyphicon-trash"></span>
                  <% end %></td>

                <% end %>   
              </td>

            <% else %>
              <td>
              <td>

              <% if current_user && current_user.adm %>
                <td>
              <%end%>
            <% end %>

          <% else %>

            
            <% if (current_user != nil) && ((current_user[:adm] == true) || User.find(post.user_id)[:id] == current_user.id)  %> 
                <td>
                <%= link_to edit_post_path(post) do %>
                  <span class="glyphicon glyphicon-edit"></span>
                <% end %></td>

            <% end %>
              

            <% if (current_user != nil) && (current_user[:adm] == true) %> 
              <td>
              <%= link_to post_dumpsters_path(post), 
                  method: :create,
                  data: { confirm: 'Are you sure you want to send this post to the Dumpster?' }  do %>
                <span class="glyphicon glyphicon-ban-circle"></span>
              <% end %>
              </td>
            <% end %>
            
              <% if (current_user != nil) && ((current_user[:adm] == true) || User.find(post.user_id)[:id] == current_user.id) %>
                <td> 
                <%= link_to post_path(post),
                    method: :delete,
                    data: { confirm: 'Are you sure you want to delete this post?' } do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <% end %></td>


              <% end %>   
              

          <% end %>

          </tr>
        </tbody>

        <% end %>
      </table>
    </div>
  </div>
</div>

project/app/views/posts/map.html.erb
<div id="kconteiner">
  <div class = "box box2">
    <div class="titles">
      <h3><span class="glyphicon glyphicon-map-marker"></span> Location</h3>
    </div>
    <%= link_to "Back to the post", @post %>
    <div id="map"></div>
  </div>
</div>
<% s=Geo.find_by(post_id: @post.id) %>

<script>
function initMap() {
  var x = <%= s.longitude.to_f %>;
  var y = <%= s.latitude.to_f %>;
  var uluru = {lat: y, lng: x};
  var map = new google.maps.Map(
    document.getElementById('map'), {zoom: 14, center: uluru});
  var marker = new google.maps.Marker({position: uluru, map: map});
};
</script>
<style>
  #map {
    height: 400px;
    width: 100%;
   }
</style>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6_GMJcolYCOnu_HyHi05w5-yS7KN0yZE&callback=initMap">
</script>

project/app/views/posts/show.html.erb
<div id="kconteiner">
	<div class = "box-posts box-posts2">
		<div class = "edit-destroy">
			<% if (current_user != nil) && InappropriateContent.find_by(user_id: current_user.id, post_id: @post.id) != nil%>
			  	<span class="glyphicon glyphicon-warning-sign"></span> Reported
			  	|
			<% end %>
			<% if @post.close == true && @post.unresolved == false %>
				<span class="glyphicon glyphicon-check"></span> Solved
				|
			<% end %>

			<% if @post.close == true %>
				Closed
			<% else %>
				Opened
			<% end %>
			<% if current_user %>
              <% g=Geofence.find_by(user_id: current_user.id) %>
              <% p=Geo.find_by(post_id: @post.id) %>
            <% else %>
              <%g=nil%>
              <%p=nil%>
            <%end%>

            <% if p && g%>
              	<% if ((g.longitude.to_f.abs - 0.1) <= p.longitude.to_f.abs && (g.longitude.to_f.abs + 0.1 >= p.longitude.to_f.abs && (g.latitude.to_f.abs - 0.1) <= p.latitude.to_f.abs && (g.latitude.to_f.abs + 0.1) >= p.latitude.to_f.abs) && current_user.adm) || (current_user.super_adm || current_user.id == @post.user_id)  %>


					<% if (current_user != nil) && ((current_user[:adm] == true) || User.find(@post.user_id)[:id] == current_user.id) %>
						| 
			      		<%= link_to edit_post_path(@post) do%>
			      			<span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> Edit
			      		<% end %>
					<% end %>
					<% if (current_user != nil) && (current_user[:adm] == true) && (@post[:inappropriate] == false) %>
						| 
		                <%= link_to post_dumpsters_path(@post), 
		                    method: :create,
		                    data: { confirm: 'Are you sure you want to send this post to the Dumpster?' }  do%>
		                    <span class="glyphicon glyphicon-ban-circle" style= "color:#FF5757"></span> Ban
		                <% end %>
		            <% end %>
		            <% if (current_user != nil) && (current_user[:adm] == true) && (@post[:inappropriate] == true) %>
						| 
		                <%= link_to dumpster_path(Dumpster.find_by(post_id: @post.id)), 
		                    method: :delete,
		                    data: { confirm: 'Are you sure you want to mark this post as Appropriate?' }  do%>
		                    <span class="glyphicon glyphicon-check" style= "color:#FF5757"></span>  Appropriate
		                <% end %>
		            <% end %>
					<% if (current_user != nil) && ((current_user[:adm] == true) || User.find(@post.user_id)[:id] == current_user.id) %>
						| 
			      		<%= link_to post_path(@post),
		                    method: :delete,
		                    data: { confirm: 'Are you sure you want to delete this post?' } do%>
		                	<span class="glyphicon glyphicon-trash" style= "color:#FF5757"></span> Delete
		                <% end %>
					
					<% end %>
				<% end %>
			<% else %> 
				<% if (current_user != nil) && ((current_user[:adm] == true) || User.find(@post.user_id)[:id] == current_user.id) %>
					| 
		      		<%= link_to edit_post_path(@post) do%>
		      			<span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> Edit
		      		<% end %>
				<% end %>
				<% if (current_user != nil) && (current_user[:adm] == true) && (@post[:inappropriate] == false) %>
					| 
	                <%= link_to post_dumpsters_path(@post), 
	                    method: :create,
	                    data: { confirm: 'Are you sure you want to send this post to the Dumpster?' }  do%>
	                    <span class="glyphicon glyphicon-ban-circle" style= "color:#FF5757"></span> Ban
	                <% end %>
	            <% end %>
	            <% if (current_user != nil) && (current_user[:adm] == true) && (@post[:inappropriate] == true) %>
					| 
	                <%= link_to dumpster_path(Dumpster.find_by(post_id: @post.id)), 
	                    method: :delete,
	                    data: { confirm: 'Are you sure you want to mark this post as Appropriate?' }  do%>
	                    <span class="glyphicon glyphicon-check" style= "color:#FF5757"></span>  Appropriate
	                <% end %>
	            <% end %>
				<% if (current_user != nil) && ((current_user[:adm] == true) || User.find(@post.user_id)[:id] == current_user.id) %>
					| 
		      		<%= link_to post_path(@post),
	                    method: :delete,
	                    data: { confirm: 'Are you sure you want to delete this post?' } do%>
	                	<span class="glyphicon glyphicon-trash" style= "color:#FF5757"></span> Delete
	                <% end %>
				
				<% end %>
			<% end %>
			

		</div>
		<h3>
			<div class = "titles">
				<strong></strong>
				<%= @post.title %>

			</div>
		</h3>
		<h5>
			<% if @post.inappropriate == true%>
				(In the Dumpster)
			<% end %>
		</h5>


		<p>
			<strong></strong>
			<a href= <%="http://localhost:3000/users/"+User.find(@post.user_id)[:id].to_s%> ><%= User.find(@post.user_id)[:name] %></a>
			<%if @post.city != "" && @post.city != nil%> 
				| <%= @post.city %>,
			<% end %>
			<%if @post.country != "" && @post.country != nil%>
				<%= @post.country %>
			<% end %>
			| 
			<%= @post.created_at.strftime( '%d/%m/%Y %H:%M' )%>

		</p>
		<% if @post.gps != "" && @post.gps != nil %>
			<p>
				<%= link_to post_map_path(@post) do%>
					<span class="glyphicon glyphicon-map-marker"></span> <%= @post.gps %>
				<% end %>
			</p>	
		<% end %>
		<p>
			<% if (current_user != nil) && (current_user[:status] == true) && (@post.inappropriate == false) && (User.find(@post.user_id)[:id] != current_user.id) %> 
				<% if Follower.find_by(user_id: current_user.id, post_id: @post.id) != nil %>
					<%= link_to post_follower_path(@post), method: :delete do%>
						<span class="glyphicon glyphicon-user" style= "color:#FF5757"></span> Unfollow
					<% end %> 
				<% else %>
		            <%= link_to post_followers_path(@post), method: :create do%>
		            	<span class="glyphicon glyphicon-user" style= "color:#FF5757"></span> Follow
		            <% end %>
		        <% end %>

		        | 
		        <% if Share.find_by(user_id: current_user.id, post_id: @post.id) != nil %>
		        	<span class="glyphicon glyphicon-share"></span> Shared
		        <% else %>
		        	<%= link_to post_shares_path(@post), method: :create do%>
		        		<span class="glyphicon glyphicon-share" style= "color:#FF5757"></span> Share
		        	<% end %>
		        <% end %>
			<% end %>  
		</p>
		

		<p>
			<div class = "description">
				<strong><%= @post.description %></strong>
			</div>
		</p>

		<p>
			<% if @post.avatar? %>
				<div class = "img-thumbnail">
					<%= image_tag @post.avatar.url(:medium) %>
				</div>
			<% end %>

		</p>
		<% if p && g%>

        	<% if ((g.longitude.to_f.abs - 0.1) <= p.longitude.to_f.abs && (g.longitude.to_f.abs + 0.1 >= p.longitude.to_f.abs && (g.latitude.to_f.abs - 0.1) <= p.latitude.to_f.abs && (g.latitude.to_f.abs + 0.1) >= p.latitude.to_f.abs) && current_user.adm) || (current_user.super_adm || current_user.id == @post.user_id)  %>

				<% if (current_user != nil) && (current_user[:adm] == true || User.find(@post.user_id)[:id] == current_user.id) && (@post[:close] == true) && (@post[:unresolved] == true) %>
					<strong>Already Solved?</strong>
		            <%= link_to 'Click here',post_path(@post, post:{unresolved: false}), 
		                method: :put %>
		        <% end %>
		    <% end %>
		<% else %>
			<% if (current_user != nil) && (current_user[:adm] == true || User.find(@post.user_id)[:id] == current_user.id) && (@post[:close] == true) && (@post[:unresolved] == true) %>
				<strong>Already Solved?</strong>
		        <%= link_to 'Click here',post_path(@post, post:{unresolved: false}), 
		                method: :put %>
		    <% end %>
		<% end %>
		

		<p>
			<%if @post.file? %>
				<iframe src= <%= @post.file.url.html_safe %> width='595' height="300" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe>
			<% end %>
		</p>
	</div><br>
	<div class = "box-comments box-comments2" >

		<% contador1 = 0 %>
		<% for like in Like.all do %>
			<% if like.post_id == @post.id %>
				<% contador1 += 1 %>
			<% end %>
		<% end %>

		<% contador2 = 0 %>
		<% for dislike in Dislike.all do %>
			<% if dislike.post_id == @post.id %>
				<% contador2 += 1 %>
			<% end %>
		<% end %>

		<br>
		<p> 
			<div id="vote"></div>
			<%=contador1%>
			<% if current_user != nil && current_user.status == true && (@post.inappropriate == false) %>
	            <% if Like.find_by(user_id: current_user.id, post_id: @post.id) != nil %>
		            <%= link_to post_like_path(@post, anchor:"vote"), method: :delete do %>
		                <span class="glyphicon glyphicon-thumbs-up"></span>
		            <% end %>
	            <% elsif Dislike.find_by(user_id: current_user.id, post_id: @post.id) != nil %>      
	            		<span class="glyphicon glyphicon-thumbs-up"></span>
	            <% else %>
	            	<%= link_to post_likes_path(@post, anchor:"vote"), method: :create do %>
		                <span class="glyphicon glyphicon-thumbs-up"></span>
		            <% end %>
	            <% end %>
            <% else %>
            	<span class="glyphicon glyphicon-thumbs-up"></span>
            <% end %>
            |
            <%=contador2%>
            <% if current_user != nil && current_user.status == true && (@post.inappropriate == false)%>
	            <% if Dislike.find_by(user_id: current_user.id, post_id: @post.id) != nil %>
		            <%= link_to post_dislike_path(@post, anchor:"vote"), method: :delete do %>
		                  <span class="glyphicon glyphicon-thumbs-down"></span>
		            <% end %>
	            <% elsif Like.find_by(user_id: current_user.id, post_id: @post.id) != nil %>      
	            	<span class="glyphicon glyphicon-thumbs-down"></span>
	            <% else %>
	            	<%= link_to post_dislikes_path(@post, anchor:"vote"), method: :create do %>
		                  <span class="glyphicon glyphicon-thumbs-down"></span>
		            <% end %>
	            <% end %>
            <% else %>
            	<span class="glyphicon glyphicon-thumbs-down"></span>
            <% end %>
        </p>
        
        <p>
            <% if (current_user != nil) && (current_user[:status] == true) && (@post.inappropriate == false) && InappropriateContent.find_by(user_id: current_user.id, post_id: @post.id) == nil%>
				  <%= link_to new_post_inappropriate_content_path(@post) do%>
				  	<span class="glyphicon glyphicon-warning-sign" style= "color:#FF5757"></span> Inappropriate
				  <% end %>
			<% end %>
		</p>

		<% if @post.close == false && (@post.inappropriate == false)%>
			<% if !(current_user == nil) && !(current_user[:status] == false) %>
				<div class = "box-comments-grey">
					<%= form_with(model: [@post, @post.comments.build], local: true) do |form| %>
						<p>
						    <%= form.label :description, "Add a comment" %><br>
						    <strong><%= form.text_area :description, :required => true %></strong>
					    </p>
					    <p>
					    	<%= form.submit "Enter" %>
					    </p>
					<% end %>
					<small class="form-text text-muted"><strong>Tag someone using @ and replacing space with "_" (e.g: Martin Concha -> @Martin_Concha)</strong></small>
				</div>
			<% end %>
			<div class = "box-comments-grey" id="comments">
				<% for comment in Comment.all.sort.reverse do %>
					<% if comment.post_id == @post.id %>
						<p>
	      					<a href= <%="http://localhost:3000/users/"+User.find(comment[:user_id])[:id].to_s%>><span class=" glyphicon glyphicon-comment" style= "color:#FF5757"></span> <%= User.find(comment[:user_id])[:name]%></a> | <strong><%= comment.created_at.strftime( '%d/%m/%Y %H:%M' )%></strong>
	      					<% if current_user != nil && current_user.id == comment.user_id %>
	      						| <%= link_to edit_post_comment_path(@post,comment,anchor:"edit-comment") do%>
	      						   <span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> Edit
	      						<% end %>

	      						| <%= link_to [comment.post, comment],
					               method: :delete,
					               data: { confirm: 'Are you sure you want to delete this comment?' } do %>
					               <span class="glyphicon glyphicon-trash" style= "color:#FF5757"></span> Delete
					              <% end %>
				            <% end %>
						</p>
						<p>	
							<div class = "description"><strong><%= comment[:description] %></strong></div>
						</p>					
						<br>
					<% end %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>