project/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }

  resources :users, path_names: { edit: 'change_password' } do
    get 'map' => 'users#map'
    resources :blacklists, only: [:create]
  end
  post '/create_user' => 'users#create', as: :create_user

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    get 'map' => 'posts#map'
    resources :inappropriate_content, only: [:new, :create]
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, only: [:create, :destroy]
    resources :followers, only: [:create, :destroy]
    resources :shares, only: [:create]
    resources :dumpsters, only: [:create]
  end
  

  resources :administrators, path_names: { edit: 'change_password' } do
    get 'map' => 'administrators#map'
    get 'map_edit' => 'administrators#map_edit'
    put 'map_edit' => 'administrators#map_update'

  end

  resources :blacklists, only: [:index, :destroy]
  resources :dumpsters, only: [:index, :destroy]
  resources :abusive_contents, only: [:new, :create]



  root 'home#index'

  get 'terms_of_services' => 'registrations#terms_of_services'


  get 'aup' => 'registrations#aup'
  get 'notifications' => 'notifications#index'

  delete '/log_in' => 'sessions#destroy', as: :log_out

end

project/app/controllers/abusive_contents_controller.rb
class AbusiveContentsController < ApplicationController
	skip_before_action :authenticate_user!, :only => [:new, :create]
	def new

	end
	def create

		NotifierMailer.send_email(ac_params[:description], ac_params[:email]).deliver
		flash[:success] = "The report was successfully send"
		redirect_to 'http://localhost:3000'
		
	end

	def ac_params
      params.require(:abusive_content).permit(:description, :email)
    end
end

project/app/helpers/abusive_content_helper.rb
module AbusiveContentHelper
end

project/app/views/abusive_contents/new.html.erb
<div id="kconteiner">
	<div class="box box2">
		<div class ="titles">
			<h1><span class="glyphicon glyphicon-warning-sign" style= "color:#FF5757"></span> Report Abusive</h1>
		</div>

		<%= form_for(:abusive_content, url: abusive_contents_path) do |form| %>

			<p>
				<%= form.label :email %>
				<%= form.email_field :email , :required => true%> 
			</p>

			<p>
				<%= form.label :description %>
				<%= form.text_area :description , :required => true%> 
			</p>

			<p>
				<br><%= form.submit "Enter", :class => 'button' %>
			</p>
		<% end %>
	</div>
</div>