project/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }

  resources :users, path_names: { edit: 'change_password' } do
    get 'map' => 'users#map'
    resources :blacklists, only: [:create]
  end
  post '/create_user' => 'users#create', as: :create_user

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    get 'map' => 'posts#map'
    resources :inappropriate_content, only: [:new, :create]
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, only: [:create, :destroy]
    resources :followers, only: [:create, :destroy]
    resources :shares, only: [:create]
    resources :dumpsters, only: [:create]
  end
  

  resources :administrators, path_names: { edit: 'change_password' } do
    get 'map' => 'administrators#map'
    get 'map_edit' => 'administrators#map_edit'
    put 'map_edit' => 'administrators#map_update'

  end

  resources :blacklists, only: [:index, :destroy]
  resources :dumpsters, only: [:index, :destroy]
  resources :abusive_contents, only: [:new, :create]



  root 'home#index'

  get 'terms_of_services' => 'registrations#terms_of_services'


  get 'aup' => 'registrations#aup'
  get 'notifications' => 'notifications#index'

  delete '/log_in' => 'sessions#destroy', as: :log_out

end

project/app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
	skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy]
	before_action :authorize_super_admin, except: [:map, :show]



	def index
    	admins = User.search(params[:search])
    	@administrators = []

    	for user in admins do 
    		if user.adm == true
    			@administrators << user
    		end
    	end
  	end

	def show
		@administrator = User.find(params[:id])
	end

	def new
		@administrator = User.new
	end

	def edit
		@administrator = User.find(params[:id])
	end

	def map_edit
		@administrator = User.find(params[:administrator_id])
	end

	def map_update
		@administrator = User.find(params[:id])

		if @administrator.update(user_params)
	      flash[:success] = "Successfully updated."
	      redirect_to 'http://localhost:3000/administrators'
	    else
	      flash[:error] = "Cannot update this admin."
	      render :edit
	    end
	end

	def create
		@administrator = User.new(user_params)

		if @administrator.save(user_params)

	    	flash[:success] = "The admin was created successfully."
	    	redirect_to @administrator
	    else
	    	flash.now[:error] = "Cannot create this admin."
	    	render :new
	    end

	end

	def map

		@user = User.find(params[:administrator_id])

	end

	def update
		@administrator = User.find(params[:id])

		if @administrator.update(user_params)
	      flash[:success] = "Successfully updated."
	      redirect_to 'http://localhost:3000/administrators/' + @administrator.id.to_s
	    else
	      flash[:error] = "Cannot update this admin."
	      render :edit
	    end
	end


	def destroy
		@administrator = User.find(params[:id])
		@administrator.destroy
		if @administrator.destroy
	      flash[:success] = "The admin was destroyed successfully."
	      redirect_to administrators_path
	    end
	end


	private 
		def set_user
    		@administrator = User.find(params[:id])
    	end

  		def user_params

			if current_user == nil
    			params.require(:administrator).permit(:name, :email, :password, :password_confirmation, :birthdate, :country, :city, :gps, :picture, :biography)
		  	else
    			params.require(:administrator).permit(:name, :email, :password, :password_confirmation, :birthdate, :country, :city, :gps, :picture, :biography).merge(aup: true, terms: true, adm: true)
			end

  		end

  		def correct_user
      		@administrator = User.find(params[:id])
      		redirect_to(root_url) unless @administrator == current_user
    	end

    	def super_adm_user
    		redirect_to(root_url) unless current_user.super_adm?
    	end



end

project/app/helpers/administrators_helper.rb
module AdministratorsHelper

end

project/app/views/administrators/edit.html.erb
<div id="kconteiner">
  <div class="box box2">
      <div class="titles">
        <h1><span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> Change Password Admin</h1>
      </div>


    <%= form_with(model: @administrator, local: true)  do |form| %>
        
        <% if @administrator.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@administrator.errors.count, "error") %> prohibited
              this article from being saved:
            </h2>
            <ul>
              <% @administrator.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <p>
          <%= form.label :password,"New password" %><br>
          <%= form.password_field :password %>
        </p>

        <p>
          <%= form.label :password_confirmation %><br>
          <%= form.password_field :password_confirmation %>
        </p>

        
     
        <p>
          <%= form.submit "Update Password", :class => 'button' %>
        </p>
    <% end %>
  </div>
</div>

project/app/views/administrators/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div id="kconteiner">
  <div class = "box box2">
    <div class = "titles">
      <h1>Administrators</h1>
    </div>

    <div class="search-container">
      <form class="example">
        <%= form_tag(administrators_path, method: :get) do %>
          <%= text_field_tag :search, params[:seach], placeholder: "Search by name or city.." %>
          <button class="button" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        <% end %><br>
      </form>
    </div>
    
    <%= link_to new_administrator_path do%>
      <span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> New Administrator
    <% end %>
    
    <div clas="table">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">City</th>
            <th scope="col">Country</th>
            <th scope="col">Last access</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @administrators.each do |admin| %>
          <tr>
            <td scope="row"><span class="glyphicon glyphicon-user"></span></td>
            <td><strong><%= admin.name %></strong></td>
            <td><strong><%= admin.email %></strong></td>
            <td><strong><%= admin.city %></strong></td>
            <td><strong><%= admin.country %></strong></td>
            <td>
                <% if admin.last_sign_in_at %>
                  <strong><%= admin.last_sign_in_at.strftime( '%d/%m/%Y %H:%M' ) %></strong>
                <% else %>
                  <strong><%= 'Has not logged yet.' %></strong>
                <% end %>
            </td>
            <td><%= link_to administrator_path(admin) do %>
                  <span class="glyphicon glyphicon-eye-open"></span>
                <% end %></td>
            <td>
              <% if (current_user != nil) && (admin.id == current_user.id)%> 
                <%= link_to edit_user_registration_path do %>
                  <span class="glyphicon glyphicon-edit"></span>
                <% end %>

                
              <% elsif (current_user != nil) && (current_user[:super_adm] == true)%> 
                <%= link_to edit_administrator_path(admin) do %>
                  <span class="glyphicon glyphicon-edit"></span>
                <% end %>

              <% end %>
              </td>
              <td>
              <% if (current_user != nil) && (current_user[:super_adm] == true)%> 
                <%= link_to administrator_map_edit_path(admin) do %>
                  <span class="glyphicon glyphicon-map-marker"></span>
                <% end %>
              <% end %>
              </td>
            
            <td><%= link_to administrator_path(admin),
                    method: :delete,
                    data: { confirm: 'Are you sure you want to delete this administrator?' } do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <% end %>  
            </td>


          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

project/app/views/administrators/map.html.erb
<div id="kconteiner">
  <div class = "box box2">
    <div class="titles">
      <h3><span class="glyphicon glyphicon-map-marker"></span> Location</h3>
    </div>
    <%= link_to "Back to administrator", 'http://localhost:3000/administrators/' + @user.id.to_s %>
    <% s=Geofence.find_by(user_id: @user.id) %><br><br>

    <h10  style="color:#00FF00"> User</h10><h10  style="color:blue"> Post</h10>
  

    <script>

    var bermudaTriangle;
    function initialize() {

        var x = <%= s.longitude.to_f %>;
        var y = <%= s.latitude.to_f %>;
        var myLatLng = new google.maps.LatLng(y, x);
        var mapOptions = {
            zoom: 10.5,
            center: myLatLng,
            mapTypeId: google.maps.MapTypeId.RoadMap
        };

        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);


        var triangleCoords = [
            new google.maps.LatLng((y-0.1), (x+0.1)),
            new google.maps.LatLng((y+0.1), (x+0.1)),
            new google.maps.LatLng((y+0.1), (x-0.1)),
            new google.maps.LatLng((y-0.1), (x-0.1))

        ];

        // Construct the polygon
        bermudaTriangle = new google.maps.Polygon({
            paths: triangleCoords,
            draggable: false,
            editable: false,
            strokeColor: '#FF0000',
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: '#FF0000',
            fillOpacity: 0.35
        });

        bermudaTriangle.setMap(map);
        google.maps.event.addListener(bermudaTriangle, "dragend");

        <% for g in Geo.all %>

            marker = new google.maps.Marker({
                position: new google.maps.LatLng(<%= g.latitude.to_f %>, <%= g.longitude.to_f %>), map: map, 
                    icon: {url: "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"},

            });
        <% end %>

        <% for g in Geofence.all %>

            marker = new google.maps.Marker({
                position: new google.maps.LatLng(<%= g.latitude.to_f %>, <%= g.longitude.to_f %>), map: map, 
                    icon: {url: "http://maps.google.com/mapfiles/ms/icons/green-dot.png"}
            });
        <% end %>


    }


    </script>
    <body onload="initialize()">

        <div id="map-canvas">
        </div>
        <div id="info">
        </div>
    </body>
    <style>
      #map {
        height: 400px;
        width: 100%;
       }

       #map-canvas {
        width: auto;
        height: 350px;
        }
        #info {
            position: absolute;
            font-family: arial, sans-serif;
            font-size: 18px;
            font-weight: bold;
        }
    </style>

    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6_GMJcolYCOnu_HyHi05w5-yS7KN0yZE">
    </script>
      </div>
</div>

project/app/views/administrators/map_edit.html.erb
<div id="kconteiner">
  <div class="box box2">
      <div class="titles">
        <h1><span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> Change Geofence</h1>
      </div>


    <%= form_with(model: @administrator, local: true)  do |form| %>
        
        <% if @administrator.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@administrator.errors.count, "error") %> prohibited
              this article from being saved:
            </h2>
            <ul>
              <% @administrator.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <p>
          <%= form.label :gps,"New address" %><br>
          <%= form.text_field :gps %>
        </p>


        
     
        <p>
          <%= form.submit "Update", :class => 'button' %>
        </p>
    <% end %>
  </div>
</div>

project/app/views/administrators/new.html.erb
<div id="kconteiner"> 
  <div class="box box2">
    <div class="titles">
      <h1><span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> New Administrator</h1>
    </div>


    <%= form_with scope: :administrator, url: administrators_path, local: true do |form| %>
        
        <% if @administrator.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@administrator.errors.count, "error") %> prohibited
              this article from being saved:
            </h2>
            <ul>
              <% @administrator.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <p>
          <%= form.label :name %><br>
          <%= form.text_field :name , :required => true%>
        </p>

        <p>
          <%= form.label :email %><br>
          <%= form.text_field :email , :required => true%>
        </p>

        <p>
          <%= form.label :password %><br>
          <%= form.password_field :password , :required => true%>
        </p>

        <p>
          <%= form.label :password_confirmation %><br>
          <%= form.password_field :password_confirmation , :required => true%>
        </p>

        <p>
          <%= form.label :birthdate %><br>
          <%= form.date_field :birthdate %>
        </p>

        <p>
          <%= form.label :city %><br>
          <%= form.text_field :city %>
        </p>

        <p>
          <%= form.label :country %><br>
          <%= form.text_field :country %>
        </p>

        <p>
          <%= form.label :gps, "Geofence (Address)" %><br>
          <%= form.text_field :gps %>
        </p>

        <p>
          <%= form.label :biography %><br>
          <%= form.text_area :biography %>
        </p>

        <p>
          <%= form.label :avatar %><br>
          <%= form.file_field :avatar %>
        </p>

        
        <p>
          <br><br><br><%= form.submit "Create", :class => 'button' %>
        </p>
    <% end %>
  </div>
</div>

project/app/views/administrators/show.html.erb
<div id="kconteiner">
  <div class = "box box2">
    <div class = "box-users box-users2" >
      <div class = "edit-destroy">
        <% if (current_user != nil) && (@administrator.id == current_user.id)%> 
          <%= link_to edit_user_registration_path do%>
            <span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> Edit
          <% end %>
          |
        <% end %>
        <% if (current_user != nil) && (current_user[:super_adm] == true) && (@administrator[:adm] == true) && (@administrator.id != current_user.id)%> 
          <%= link_to edit_administrator_path(@administrator) do%>
            <span class="glyphicon glyphicon-edit" style= "color:#FF5757"></span> Change Password
          <% end %>
          |
          <%= link_to administrator_map_edit_path(@administrator) do%>
            <span class="glyphicon glyphicon-map-marker" style= "color:#FF5757"></span> Change Geofence
          <% end %>
          |
        <% end %>



        <% if (current_user != nil) && ((current_user[:super_adm] == true) || @administrator.id == current_user.id)%> 
          <%= link_to administrator_path(@administrator),
                      method: :delete,
                      data: { confirm: 'Are you sure you want to delete this administrator?' } do%>
                      <span class="glyphicon glyphicon-trash" style= "color:#FF5757"></span> Delete
          <% end %>
        <% end %>
      </div>
      <% if @administrator.avatar? %>
        <div class = "img-user">      
          <p>
            <%= image_tag @administrator.avatar.url(:medium) %>
          </p>
        </div>
      <% end %>
      <div class = "box-user-profile">
        <div class = "titles"><h2>
          <%= @administrator.name %>

        </h2></div>
        <% contador1 = 0 %>
        <% for like in Like.all do %>
          <% if like.user_id == @administrator.id %>
            <% contador1 += 1 %>
          <% end %>
        <% end %>

        <% contador2 = 0 %>
        <% for dislike in Dislike.all do %>
          <% if dislike.user_id == @administrator.id %>
            <% contador2 += 1 %>
          <% end %>
        <% end %>
        <% contador3 = 0 %>
        <% for comment in Comment.all do %>
          <% if comment.user_id == @administrator.id %>
            <% contador3 += 1 %>
          <% end %>
        <% end %>
        <p>
          <%= contador1%> <span class="glyphicon glyphicon-thumbs-up"></span>  
          <%= contador2%> <span class="glyphicon glyphicon-thumbs-down"></span>       
          <%= contador3%> <span class="glyphicon glyphicon-comment"></span> 
        </p>

        <% if (current_user != nil) && (current_user[:super_adm] == true )%> 
          <p>
            <span class="glyphicon glyphicon-log-in"></span>  Last Access:
            <% if @administrator.last_sign_in_at %>
              <strong><%= @administrator.last_sign_in_at.strftime( '%d/%m/%Y %H:%M' )%></strong>
            <% else %>
              <strong><%= 'Has not logged yet.' %></strong>
            <% end %>
          </p>
          <p>
            <span class="glyphicon glyphicon-user"></span> Role:
            <% if @administrator[:super_adm] == true %>
              <strong>Super Admin</strong>
            <% elsif @administrator[:adm] == true %>
              <strong>Admin</strong>
            <% else %>
              <strong>User</strong>
            <% end %>
          </p>
        <% end %>

         
        <p>
          <strong><span class="glyphicon glyphicon-envelope"></span>  <%= @administrator.email %></strong>
        </p>

        <p>
          <strong><span class="glyphicon glyphicon-map-marker"></span>  <%= @administrator.city %>, <%= @administrator.country %></strong>
        </p>

        <% if @administrator.gps != "" && @administrator.gps != nil %>
          <p>
            <%= link_to administrator_map_path(@administrator) do%>
              <span class="glyphicon glyphicon-map-marker"></span> Geofence
            <% end %>
          </p>  
        <% end %>

        <p>
          <strong><span class="glyphicon glyphicon-info-sign"></span> <%= @administrator.biography %></strong>
        </p>
      </div>
    </div>
  </div>

  <div class="box-separator"><br>
  </div>
  <div class="box-separator-white"><br>
  </div>

  <div class = "box-users box-users2">
    <table class='table'>
      <% for post in Post.all.sort.reverse do %>
        <% if post.user_id == @administrator.id && post.inappropriate == false%>
          <tr>
            <td>
              <a href= <%="http://localhost:3000/posts/"+Post.find(post.id)[:id].to_s%>><span class="glyphicon glyphicon-file" style= "color:#FF5757"></span> <%= Post.find(post.id)[:title] %></a> | <%= post.created_at.to_s %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>

  <div class="box-separator"><br>
  </div>
  <div class="box-separator-white"><br>
  </div>

  <strong>
  <div class = "box-users box-users2">
    <div class='table'>
      <table clas='table'>
        <%wall = [] %>
        <% for wall in UserProfile.all.sort.reverse{ |e| e.created_at} do %>
          <% if wall.user_id == @administrator.id %>
            <tr>
              <td>
                <% if wall.help == "like" %>
                  <span class="glyphicon glyphicon-thumbs-up"></span> <%= wall.description %>
                <% elsif wall.help == "dislike" %>
                  <span class="glyphicon glyphicon-thumbs-down"></span> <%= wall.description %>
                <% elsif wall.help == "post" %>
                  <span class="glyphicon glyphicon-file"></span> <%= wall.description %>
                <% elsif wall.help == "comment" %>
                  <span class="glyphicon glyphicon-comment"> </span> <%= wall.description %>
                <% elsif wall.help == "share" %>
                  <span class="glyphicon glyphicon-share"></span> <%= wall.description %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
  </strong>
</div>